POST http://localhost:8000/api/links
Content-Type: application/json


{
    "code": "Gooogle",
    "url": "https://www.google.com"
}


###
GET http://localhost:8000/api/links

###
GET http://localhost:8000/Gooogle

###
GET http://localhost:8000/api/analytics