POST http://localhost:8000/api/links
Content-Type: application/json


{
    "code": "google",
    "url": "https://www.google.com"
}


###
GET http://localhost:8000/api/links

###
GET http://localhost:8000/google

###
GET http://localhost:8000/api/analytics

###
GET http://localhost:8000