version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=urlshortener
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/bitnami/postgresql/data

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=redispwd
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis

volumes:
  postgres_data:
  redis_data: